exports.seed = async function (knex) {
	// Deletes ALL existing entries
	await knex('books').del()
	await knex('books').insert([
		{
			id: 1,
			title: 'Fundamental Mathematics',
			author: 'J.P Udoh Umoh',
			description: 'A basic and easy introduction to mathematics for the brilliant minds',
			in_stock: 23,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 2,
			title: 'Introduction to Computer Engineering',
			author: 'John Smith',
			description: 'A comprehensive guide to the principles and practices of computer engineering',
			in_stock: 15,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 3,
			title: 'Digital Logic and Computer Design',
			author: 'M. Morris Mano',
			description: 'An in-depth exploration of digital logic circuits and computer design principles',
			in_stock: 8,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 4,
			title: 'Computer Organization and Design',
			author: 'David A. Patterson, John L. Hennessy',
			description: 'A comprehensive introduction to the organization and design of computer systems',
			in_stock: 12,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 5,
			title: 'Operating System Concepts',
			author: 'Abraham Silberschatz, Peter B. Galvin, Greg Gagne',
			description: 'A foundational book on operating system principles and concepts',
			in_stock: 5,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 6,
			title: 'Computer Networks',
			author: 'Andrew S. Tanenbaum, David J. Wetherall',
			description: 'A comprehensive guide to computer networking concepts and protocols',
			in_stock: 9,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 7,
			title: 'Database Systems: The Complete Book',
			author: 'Hector Garcia-Molina, Jeffrey D. Ullman, Jennifer Widom',
			description: 'A comprehensive book on database systems and concepts',
			in_stock: 6,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 8,
			title: 'Algorithms',
			author: 'Robert Sedgewick, Kevin Wayne',
			description: 'A classic textbook on algorithms and data structures',
			in_stock: 10,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 9,
			title: 'Introduction to the Theory of Computation',
			author: 'Michael Sipser',
			description: 'An introduction to the theory of computation and formal languages',
			in_stock: 7,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 10,
			title: 'Computer Architecture: A Quantitative Approach',
			author: 'John L. Hennessy, David A. Patterson',
			description: 'A comprehensive book on computer architecture and performance evaluation',
			in_stock: 14,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 11,
			title: 'Introduction to Embedded Systems',
			author: 'Edward Ashford Lee, Sanjit Arunkumar Seshia',
			description: 'A comprehensive guide to embedded systems design and programming',
			in_stock: 4,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 12,
			title: 'Computer Graphics: Principles and Practice',
			author: 'John F. Hughes, Andries van Dam, Morgan McGuire, David F. Sklar, James D. Foley, Steven K. Feiner, Kurt Akeley',
			description: 'A comprehensive introduction to computer graphics principles and techniques',
			in_stock: 11,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 13,
			title: 'Introduction to Automata Theory, Languages, and Computation',
			author: 'John E. Hopcroft, Rajeev Motwani, Jeffrey D. Ullman',
			description: 'A classic book on automata theory, formal languages, and computation',
			in_stock: 3,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 14,
			title: 'Computer Security: Principles and Practice',
			author: 'William Stallings, Lawrie Brown',
			description: 'A comprehensive guide to computer security principles and practices',
			in_stock: 9,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 15,
			title: 'Introduction to Data Mining',
			author: 'Pang-Ning Tan, Michael Steinbach, Vipin Kumar',
			description: 'An introductory book on the principles and techniques of data mining',
			in_stock: 6,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 16,
			title: 'Introduction to Artificial Intelligence',
			author: 'Philip C. Jackson',
			description: 'A comprehensive introduction to the field of artificial intelligence',
			in_stock: 8,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 17,
			title: `Software Engineering: A Practitioner's Approach`,
			author: 'Roger S. Pressman',
			description: 'A practical guide to software engineering principles and methodologies',
			in_stock: 7,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 18,
			title: 'Introduction to Machine Learning',
			author: 'Ethem Alpaydin',
			description: 'An introductory book on machine learning algorithms and concepts',
			in_stock: 5,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 19,
			title: 'Computer Vision: Algorithms and Applications',
			author: 'Richard Szeliski',
			description: 'A comprehensive book on computer vision algorithms and applications',
			in_stock: 7,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
		{
			id: 20,
			title: 'Introduction to Cryptography',
			author: 'Johannes Buchmann',
			description: 'An introduction to the principles and techniques of cryptography',
			in_stock: 4,
			created_at: knex.fn.now(),
			updated_at: knex.fn.now(),
		},
	])
}
